### ISSUE TITLE
Pourquoi n'y a t-il pas la lettre dans les ID ?

### ISSUE THREAD

**Issue by theFreedomBanana** [SocialGouv/codes-naf#4]
Bonjour,
Merci pour le package ! Mais pourquoi n'y a t-il pas la lettre dans les ID ? Est ce un oubli ou bien y a t-il une raison valable ?
Cordialement

**Comment by revolunet** [comment]
Bonjour,

A priori nous nous sommes basés sur ces données : https://www.insee.fr/fr/information/2120875

On voit les ID et les memes avec des `Z` en plus en suffixe. vous parlez de cela ?


<img width="819" alt="Capture d’écran 2023-05-16 à 17 11 28" src="https://github.com/SocialGouv/codes-naf/assets/124937/61681f13-9382-4b2d-a049-6642ed843515">

**Comment by theFreedomBanana** [comment]
Oui je parle bien de ça. Il semblerai que la lettre corresponde au 4ème niveau de spécificité du code qui sont :
- Divison : 2 chiffres
- Groupe : 1 chiffre
- Classe : 1chiffre
- Sous Classe : 1 lettre
En prenant l'exemple du code '87.10' (Hébergement médicalisé), il existe 3 sous classes différentes :
- A : Hébergement médicalisé pour personnes âgées
- B : Hébergement médicalisé pour enfants handicapés
- C : Hébergement médicalisé pour adultes handicapés et autre hébergement médicalisé

Si je comprends bien il manque donc les Sous Classes dans le package ?

**Comment by revolunet** [comment]
J'ai ajouté les sous-classes dans [cette pull request](https://github.com/SocialGouv/codes-naf/pull/5)

Si cela vous est utile, on peut intégrer cela dans la prochaine livraison

**Comment by theFreedomBanana** [comment]
@revolunet désolé pour ma réponse tardive. Je n'en aurais personnellement pas besoin mais je pense néanmoins que ce serait un plus pour le package. Quoi qu'il en soit merci de vous en être occupé !
Bonne journée :)
