### ISSUE TITLE
Invalid ids in index.json

### ISSUE THREAD

**Issue by trikrow** [SocialGouv/codes-naf#6]
Hello, 
I just noticed in the last commit some ids are incorrect (lines **6414**, and **6417** for example).

And just to verify, what was added in this version is just the different levels for existing code NAFs ? No new codes were added ?
 Thank you !

**Comment by revolunet** [comment]
Good catch, thanks for reporting.
Looks like 2 errors were due to initial data conversion.

Fixed in the next release : https://github.com/SocialGouv/codes-naf/pull/7
